server:
  port: 9090

# mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/waimai?useUnicode=true&&useSSL=false&&characterEncoding=UTF-8&&serverTimezone=GMT%2B8
    username: root
    password: 1234

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.redsea.waimai.mapper
  mapper-locations: classpath:mapper/*.xml
