package com.redsea.waimai.model;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.user_id
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.contacts
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    private String contacts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.contacts_mobile
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    private Integer contactsMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.house_number
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    private String houseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.tag
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.user_id
     *
     * @return the value of address.user_id
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.user_id
     *
     * @param userId the value for address.user_id
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.contacts
     *
     * @return the value of address.contacts
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.contacts
     *
     * @param contacts the value for address.contacts
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.contacts_mobile
     *
     * @return the value of address.contacts_mobile
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public Integer getContactsMobile() {
        return contactsMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.contacts_mobile
     *
     * @param contactsMobile the value for address.contacts_mobile
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public void setContactsMobile(Integer contactsMobile) {
        this.contactsMobile = contactsMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address
     *
     * @return the value of address.address
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address
     *
     * @param address the value for address.address
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.house_number
     *
     * @return the value of address.house_number
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public String getHouseNumber() {
        return houseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.house_number
     *
     * @param houseNumber the value for address.house_number
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public void setHouseNumber(String houseNumber) {
        this.houseNumber = houseNumber == null ? null : houseNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.tag
     *
     * @return the value of address.tag
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.tag
     *
     * @param tag the value for address.tag
     *
     * @mbg.generated Sun Apr 05 17:40:45 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }
}